version: "3.9"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-CU1-ubuntu-20.04
    container_name: 'sqlserver'
    environment:
      ACCEPT_EULA="Y"
      MSSQL_SA_PASSWORD="TestJobsity2023"
      MSSQL_PID="Developer"
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log

  rabbitmq:
    image: rabbitmq:3.11.9-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbit:/var/lib/rabbitmq/
      - rabbit:/var/log/rabbitmq